# Generated by Django 5.2.8 on 2026-02-11 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=120)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=50)),
                ('doctor', models.CharField(blank=True, default='Dr. Alejandro Gomez', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.paciente')),
            ],
        ),
    ]
