# Generated by Django 5.2.8 on 2026-02-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='eps',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
