# Generated by Django 5.2.8 on 2026-02-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_paciente_eps_paciente_tipo_sangre'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('programada', 'Programada'), ('asistida', 'Asistida'), ('pospuesta', 'Pospuesta'), ('cancelada', 'Cancelada')], default='programada', max_length=20),
        ),
    ]
